### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by kip0x00** [vonhoff/Serilog.Sinks.RichTextBox.WinForms.Colored#15]
Hi!
I tried your control, it's fantastic!
Thank you for spending so much time and effort!
I like everything so far, but I'm faced with one problem that I can't solve myself, I have very little programming experience. I needed to change the font size at any time during the operation of the program, just as, for example, I can change the number of lines displayed. Unfortunately, I have not been able to solve this problem. Could you help me with this?
PS I'm sorry for my English.

**Comment by vonhoff** [comment]
I don't think it's necessary to update the font size via the Serilog sink. You could try the following to dynamically change the font size, assuming your RichTextBox is named `richTextBox1`:
```
public void ChangeFontSize(int fontSize)
{
    // Change existing text
    richTextBox1.SelectAll();
    richTextBox1.SelectionFont = new Font(richTextBox1.Font.FontFamily, fontSize);
    
    // Change default font for new text
    richTextBox1.Font = new Font(richTextBox1.Font.FontFamily, fontSize);
    
    // Clear selection
    richTextBox1.SelectionStart = richTextBox1.TextLength;
    richTextBox1.SelectionLength = 0;
}
```

**Comment by kip0x00** [comment]
Thanks for the answer!
Unfortunately, this does not work properly, I did about that, the problem is as follows:
if you select an existing text and apply a new font size to it, it works:
``
RichTextBox Log.Select All();
richTextBoxLog.Selection Font = new Font(richTextBoxLog.Font.FontFamily, fontSize);
``
but further output continues with the previous font size, and if you do this:
``
richTextBoxLog.Font = new Font(richTextBoxLog.Font.FontFamily, fontSize);
```
that previous formatting breaks down (everything becomes monochrome) and further output also continues with the previous font size.

**Comment by vonhoff** [comment]
I'll take a look at it when I have more time, which might be sometime next week.

**Comment by vonhoff** [comment]
You can try this:
```
public void ChangeFontSize(int fontSize)
{
    // Store current selection
    int currentSelectionStart = richTextBox1.SelectionStart;
    int currentSelectionLength = richTextBox1.SelectionLength;

    // Change existing text while preserving colors and other formatting
    richTextBox1.SelectAll();
    using (var newFont = new Font(richTextBox1.SelectionFont.FontFamily, fontSize, richTextBox1.SelectionFont.Style))
    {
        // Save current colors
        Color currentBackColor = richTextBox1.SelectionBackColor;
        Color currentForeColor = richTextBox1.SelectionColor;

        richTextBox1.SelectionFont = newFont;

        // Restore colors
        richTextBox1.SelectionBackColor = currentBackColor;
        richTextBox1.SelectionColor = currentForeColor;
    }

    // Set default font for new text
    richTextBox1.SelectionStart = richTextBox1.TextLength;
    richTextBox1.SelectionLength = 0;
    using (var defaultFont = new Font(richTextBox1.Font.FontFamily, fontSize))
    {
        richTextBox1.SelectionFont = defaultFont;
    }

    // Restore original selection
    richTextBox1.SelectionStart = currentSelectionStart;
    richTextBox1.SelectionLength = currentSelectionLength;
}
```
This is my last attempt to resolve this issue, I believe this issue is not related to this sink, so I cannot provide any further support on this matter. I hope this works for you.

**Comment by kip0x00** [comment]
Hi @vonhoff !
Thanks for trying to help. Looking at your last code, I get the impression that you misunderstood me because of my poor English. Replacing the font of the entire text in richTextBox1 works great! I can't continue to output new text with a new font size, see the last line:
![image](https://github.com/user-attachments/assets/91d39db6-6d49-4d46-8570-e17793008620)
я минимизировал проект, чтобы показать, что я делаю:
