### ISSUE TITLE
how to disable autoscroll?

### ISSUE THREAD

**Issue by etelo** [vonhoff/Serilog.Sinks.RichTextBox.WinForms.Colored#2]
how to disable autoscroll?

**Comment by vonhoff** [comment]
It's not available in the current release, but it sounds like a good feature. In case you need it now, I've created a branch called "config_autoscroll" (see  #3). It currently contains the necessary changes to disable autoscroll, which you can do by setting the autoScroll property to false in the logger configuration. I will make a new release later this week.

**Comment by etelo** [comment]
Thank you 😊

**Comment by vonhoff** [comment]
I just released it as v1.2.0, let me know if you have any questions or encounter any bugs.
https://www.nuget.org/packages/Serilog.Sinks.RichTextBox.WinForms.Colored/1.2.0
