### ISSUE TITLE
How to use with RichTextBox if it is initialized at any time of program life?

### ISSUE THREAD

**Issue by Hiprox** [vonhoff/Serilog.Sinks.RichTextBox.WinForms.Colored#4]
The idea is to open the "console" _(form with RichTextBox)_ by pressing a keyboard shortcut.
How do you do this if you are supposed to have the RichTextBox already initialized?

**Comment by Hiprox** [comment]
> In a separate form or in the same form?
In separate form.

I am trying to create RichTextBox object in Program.cs in Main method, but when I call new TerminalForm(Program.RichTextBox) from the main form, I get an exception that it is not created in UI thread.

And if I initialize the RichTextBox object on the main form, I can't bind it to the logger, because the logger is built in Program.cs in the Main method.

**Comment by vonhoff** [comment]
I think I have it working, I just made a draft of the following:
```C#
using Serilog;
using Serilog.Events;

namespace TestApp
{
    public partial class MainForm : Form
    {
        private readonly TerminalForm _terminalForm;

        public MainForm()
        {
            InitializeComponent();
            _terminalForm = new TerminalForm();
            _terminalForm.Show();
            _terminalForm.Hide();

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.RichTextBox(_terminalForm.OutputBox, LogEventLevel.Debug)
                .CreateLogger();

            Log.Information("Started logger!");
        }

        private void btnOpenTerminal_Click(object sender, EventArgs e)
        {
            _terminalForm.Show();
        }
    }
}
```
Does this work for you too?
